#---
# Excerpted from "Agile Web Development with Rails, 2nd Ed.",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails2 for more book information.
#---
# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "line_items", :force => true do |t|
    t.column "product_id", :integer, :default => 0, :null => false
    t.column "quantity", :integer, :default => 0, :null => false
    t.column "unit_price", :integer, :default => 0, :null => false
  end

  add_index "line_items", ["product_id"], :name => "fk_line_item"

  create_table "products", :force => true do |t|
    t.column "title", :string
    t.column "description", :text
    t.column "image_url", :string
    t.column "price", :integer, :default => 0
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

end
